### ISSUE TITLE
[JB plugin] Internal error: AlreadyDisposedException

### ISSUE THREAD

**Issue by GANFI** [smallcloudai/refact-intellij#150]
An internal error happened in the IDE plugin.

Message: (no message)

### Stack trace
```
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.smallcloud.refactai.statistic.UsageStats because container is already disposed (container=Project(name=Leaflet.PixiOverlay, containerState=DISPOSE_COMPLETED, componentStore=/Users/ganfi/PhpstormProjects/frelance/Leaflet.PixiOverlay) (disposed))
	at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:40)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:698)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:630)
	at com.smallcloud.refactai.statistic.UsageStats$Companion.getInstance(UsageStats.kt:109)
	at com.smallcloud.refactai.io.AsyncConnection$send$2$2.failed(AsyncConnection.kt:218)
	at org.apache.hc.core5.concurrent.BasicFuture.failed(BasicFuture.java:138)
	at org.apache.hc.core5.concurrent.ComplexFuture.failed(ComplexFuture.java:79)
	at org.apache.hc.client5.http.impl.async.InternalAbstractHttpAsyncClient$2.failed(InternalAbstractHttpAsyncClient.java:350)
	at org.apache.hc.client5.http.impl.async.AsyncRedirectExec$1.failed(AsyncRedirectExec.java:248)
	at org.apache.hc.client5.http.impl.async.AsyncHttpRequestRetryExec$1.failed(AsyncHttpRequestRetryExec.java:197)
	at org.apache.hc.client5.http.impl.async.AsyncProtocolExec$1.failed(AsyncProtocolExec.java:295)
	at org.apache.hc.client5.http.impl.async.H2AsyncMainClientExec$1.failed(H2AsyncMainClientExec.java:119)
	at org.apache.hc.core5.http2.impl.nio.ClientH2StreamHandler.failed(ClientH2StreamHandler.java:253)
	at org.apache.hc.core5.http2.impl.nio.AbstractH2StreamMultiplexer$H2Stream.reset(AbstractH2StreamMultiplexer.java:1668)
	at org.apache.hc.core5.http2.impl.nio.AbstractH2StreamMultiplexer.onException(AbstractH2StreamMultiplexer.java:678)
	at org.apache.hc.core5.http2.impl.nio.AbstractH2IOEventHandler.exception(AbstractH2IOEventHandler.java:91)
	at org.apache.hc.core5.http2.impl.nio.ClientH2IOEventHandler.exception(ClientH2IOEventHandler.java:39)
	at org.apache.hc.core5.reactor.InternalDataChannel.onException(InternalDataChannel.java:180)
	at org.apache.hc.core5.reactor.InternalChannel.handleIOEvent(InternalChannel.java:55)
	at org.apache.hc.core5.reactor.SingleCoreIOReactor.processEvents(SingleCoreIOReactor.java:178)
	at org.apache.hc.core5.reactor.SingleCoreIOReactor.doExecute(SingleCoreIOReactor.java:127)
	at org.apache.hc.core5.reactor.AbstractSingleCoreIOReactor.execute(AbstractSingleCoreIOReactor.java:86)
	at org.apache.hc.core5.reactor.IOReactorWorker.run(IOReactorWorker.java:44)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

### Environment
- Plugin version: 1.2.25
- IDE: PhpStorm 2023.2.3  Build #PS-232.10072.32
- JDK: 17.0.8.1; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
- OS: macOS 14.5
- ARCH: aarch64
- MODE: Cloud
- LSP BUILD INFO: {"build_os":"macos-aarch64","cargo_version":"cargo 1.78.0 (54d8815d0 2024-03-26)","commit":"2c0b45588e98366b70b41c6814488ff7e2fd61cd","rust_version":"rustc 1.78.0 (9b00956e5 2024-04-29)","version":"0.8.0"}

**Comment by pixkk** [comment]
Also have problem:
### Environment
- Plugin version: 1.3.1
- IDE: IntelliJ IDEA 2023.2.2  Build #IU-232.9921.47
- JDK: 17.0.8; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
- OS: Windows 10.0
- ARCH: amd64
- MODE: Cloud
- LSP BUILD INFO: {"build_os":"windows-x86_64","cargo_version":"cargo 1.78.0 (54d8815d0 2024-03-26)","commit":"20da12c66bf1dea5aa3624e560f3b7bff9cbf129","rust_version":"rustc 1.78.0 (9b00956e5 2024-04-29)","version":"0.8.2"}

**Comment by reymondzzzz** [comment]
thank you for report. We will fix that ASAP

**Comment by MarcMcIntosh** [comment]
Looks like it was fixed in a more recent version, 

Update and let us know if you run into any more issues :)
