### ISSUE TITLE
[JB plugin] Internal error: ExecutionException

### ISSUE THREAD

**Issue by Genius-code** [smallcloudai/refact-intellij#196]
An internal error happened in the IDE plugin.

Message: Unhandled exception in [ComponentManager(ProjectImpl@1018946295), com.intellij.codeWithMe.ClientIdContextElementPrecursor@11901bc9, CoroutineName(com.intellij.internal.statistic.service.fus.collectors.ProjectFUStateUsagesLogger), Dispatchers.Default]

### Stack trace
```
java.util.concurrent.ExecutionException: org.apache.hc.core5.http2.H2StreamResetException: Timeout due to inactivity (30 SECONDS)
	at org.apache.hc.core5.concurrent.BasicFuture.getResult(BasicFuture.java:72)
	at org.apache.hc.core5.concurrent.BasicFuture.get(BasicFuture.java:85)
	at com.smallcloud.refactai.lsp.LSPProcessHolder.fetchCustomization(LSPProcessHolder.kt:269)
	at com.smallcloud.refactai.code_lens.RefactCodeVisionProviderFactory.createProviders(RefactCodeVisionProviderFactory.kt:37)
	at com.intellij.codeInsight.codeVision.CodeVisionProviderFactory$Companion.createAllProviders(CodeVisionProviderFactory.kt:16)
	at com.intellij.codeInsight.codeVision.settings.CodeVisionInlaySettingProvider.createModels(CodeVisionInlaySettingProvider.kt:17)
	at com.intellij.codeInsight.hints.InlayProviderUsageCollector.getMetrics(InlayProviderUsageCollector.kt:128)
	at com.intellij.internal.statistic.service.fus.collectors.ProjectUsagesCollector.collect$lambda$2(ProjectUsagesCollector.kt:81)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContextInner(coroutines.kt:341)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invokeSuspend(coroutines.kt:233)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:261)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:232)
	at com.intellij.internal.statistic.service.fus.collectors.ProjectUsagesCollector.collect$suspendImpl(ProjectUsagesCollector.kt:80)
	at com.intellij.internal.statistic.service.fus.collectors.ProjectUsagesCollector.collect(ProjectUsagesCollector.kt)
	at com.intellij.internal.statistic.service.fus.collectors.ProjectFUStateUsagesLogger$logProjectState$2$1.invokeSuspend(FUStateUsagesLogger.kt:228)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [ComponentManager(ProjectImpl@1018946295), com.intellij.codeWithMe.ClientIdContextElementPrecursor@11901bc9, CoroutineName(com.intellij.internal.statistic.service.fus.collectors.ProjectFUStateUsagesLogger), StandaloneCoroutine{Cancelled}@58df90e8, Dispatchers.Default]
Caused by: org.apache.hc.core5.http2.H2StreamResetException: Timeout due to inactivity (30 SECONDS)
	at org.apache.hc.core5.http2.impl.nio.AbstractH2StreamMultiplexer.onTimeout(AbstractH2StreamMultiplexer.java:558)
	at org.apache.hc.core5.http2.impl.nio.AbstractH2IOEventHandler.timeout(AbstractH2IOEventHandler.java:83)
	at org.apache.hc.core5.http2.impl.nio.ClientH2IOEventHandler.timeout(ClientH2IOEventHandler.java:39)
	at org.apache.hc.core5.reactor.InternalDataChannel.onTimeout(InternalDataChannel.java:169)
	at org.apache.hc.core5.reactor.InternalChannel.checkTimeout(InternalChannel.java:67)
	at org.apache.hc.core5.reactor.SingleCoreIOReactor.checkTimeout(SingleCoreIOReactor.java:241)
	at org.apache.hc.core5.reactor.SingleCoreIOReactor.validateActiveChannels(SingleCoreIOReactor.java:168)
	at org.apache.hc.core5.reactor.SingleCoreIOReactor.doExecute(SingleCoreIOReactor.java:130)
	at org.apache.hc.core5.reactor.AbstractSingleCoreIOReactor.execute(AbstractSingleCoreIOReactor.java:86)
	at org.apache.hc.core5.reactor.IOReactorWorker.run(IOReactorWorker.java:44)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

### Environment
- Plugin version: 5.2.0
- IDE: PhpStorm 2024.3  Build #PS-243.21565.202
- JDK: 21.0.5; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
- OS: macOS 15.1.1
- ARCH: aarch64
- MODE: Cloud
- LSP BUILD INFO: {"version":"0.10.3","commit":"1130d61dfe09a96279ec94882e51c28e234e6c9c","build_os":"macos-aarch64","rust_version":"rustc 1.82.0 (f6e511eec 2024-10-15)","cargo_version":"cargo 1.82.0 (8f40fc59f 2024-08-21)"}

**Comment by MarcMcIntosh** [comment]
Hello,

Thanks for reporting this issue, updating to version 6.3.0 or above should fix this issue

https://github.com/smallcloudai/refact-intellij/commit/c2958962a9d2446d124b7405eece0b2f38a84a2d
