### ISSUE TITLE
[JB plugin] Internal error: Default]

### ISSUE THREAD

**Issue by AsimutMLS** [smallcloudai/refact-intellij#44]
An internal error happened in the IDE plugin.

Message: *** exception class was changed or removed

### Stack trace
```
  Unhandled exception in [CoroutineName(com.smallcloud.refactai.Initializer), StandaloneCoroutine{Cancelling}@5fbb50fe, Dispatchers.Default]
  
  java.nio.file.AccessDeniedException: C:\Users\Asimut\.refact\bin\refact-lsp.exe
at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
at java.base/java.nio.file.Files.deleteIfExists(Files.java:1191)
at java.base/java.nio.file.Files.copy(Files.java:3148)
at com.smallcloud.refactai.lsp.LSPProcessHolder.startup(LSPProcessHolder.kt:101)
at com.smallcloud.refactai.Initializer.initialize(Initializer.kt:55)
at com.smallcloud.refactai.Initializer.execute(Initializer.kt:25)
at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1$1.invokeSuspend(StartupManagerImpl.kt:534)
at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1$1.invoke(StartupManagerImpl.kt)
at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1$1.invoke(StartupManagerImpl.kt)
at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1.invokeSuspend(StartupManagerImpl.kt:532)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(com.smallcloud.refactai.Initializer), StandaloneCoroutine{Cancelled}@5fbb50fe, Dispatchers.Default]

```

### Environment
- Plugin version: 1.2.3
- IDE: IntelliJ IDEA 2023.2.5  Build #IU-232.10227.8
- JDK: 17.0.9; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
- OS: Windows 10.0
- MODE: Cloud

**Comment by pixkk** [comment]
+. Have same problem. 1.2.4 version.

**Comment by reymondzzzz** [comment]
Hi! try new 1.2.5 version. Hope it helps you.

**Comment by pixkk** [comment]
Unfortunately the problem was not solved🥲. The code editor itself is run as administrator.
К сожалению проблема не решилась🥲. Редактор кода открыт от имени администратора.

```
Unhandled exception in [CoroutineName(com.smallcloud.refactai.Initializer), StandaloneCoroutine{Cancelling}@5fd46318, Dispatchers.Default]
  
  java.nio.file.AccessDeniedException: C:\Users\User\AppData\Local\Temp\refact-lsp.exe
at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
at java.base/java.nio.file.Files.deleteIfExists(Files.java:1191)
at java.base/java.nio.file.Files.copy(Files.java:3148)
at com.smallcloud.refactai.lsp.LSPProcessHolder.startup(LSPProcessHolder.kt:102)
at com.smallcloud.refactai.Initializer.initialize(Initializer.kt:52)
at com.smallcloud.refactai.Initializer.execute(Initializer.kt:25)
at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1$1.invokeSuspend(StartupManagerImpl.kt:534)
at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1$1.invoke(StartupManagerImpl.kt)
at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1$1.invoke(StartupManagerImpl.kt)
at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1.invokeSuspend(StartupManagerImpl.kt:532)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(com.smallcloud.refactai.Initializer), StandaloneCoroutine{Cancelled}@5fd46318, Dispatchers.Default]
```

**Comment by reymondzzzz** [comment]
@pixkk Could you check permissions to C:\Users\User\AppData\Local\Temp\? Looks like plugin can not copy binary backend in this directory.

**Comment by pixkk** [comment]
> @pixkk Could you check permissions to C:\Users\User\AppData\Local\Temp? Looks like plugin can not copy binary backend in this directory.

Windows user "User" can edit, manage, delete files in this folder.
![image](https://github.com/smallcloudai/refact-intellij/assets/30828435/c43916f4-a1f4-41a5-88c9-eb96ee0b9c5f)

And refact-lsp.exe is here ()

**Comment by reymondzzzz** [comment]
Wow...it's very strange :D and if you start ide with plugin right now you will get this error?

**Comment by reymondzzzz** [comment]
Could you try eap version?

insert https://plugins.jetbrains.com/plugins/eap/list in marketplace and reopen plugin settings
<img width="896" alt="image" src="https://github.com/smallcloudai/refact-intellij/assets/15812493/eb4fbe5e-7567-4d68-9ac0-24f72542d684">
<img width="489" alt="image" src="https://github.com/smallcloudai/refact-intellij/assets/15812493/a663c44e-4219-43f7-9c18-21fd6d4e3a11">

**Comment by pixkk** [comment]
![image](https://github.com/smallcloudai/refact-intellij/assets/30828435/3703dd5f-1fe0-46d8-89f8-47ec83c0b356)
In logs everything is ok (about code completion), but autocompletion is not work :(

**Comment by reymondzzzz** [comment]
Try without admin privacy pls

**Comment by pixkk** [comment]
![image](https://github.com/smallcloudai/refact-intellij/assets/30828435/5683a6df-2d7b-4960-9a28-e2018d83d554)
Yeah, it`s work now! But exist bug (but it does not affect the operation of the plugin - it works successfully).

1. Open IDE. 
2. Try open another project
3. You receive error Unhandled exception in [CoroutineName(com.smallcloud.refactai.Initializer), StandaloneCoroutine{Cancelling}@5fbb50fe, Dispatchers.Default]  java.nio.file.AccessDeniedException: C:\Users\Asimut\.refact\bin\refact-lsp.exe
4. Change project - the error no longer occurs until the IDE is restarted

**Comment by reymondzzzz** [comment]
Hmmm... You opened Ide and there wasn't error, but after opening new project you got AccessDeniedException. Am I right?
