### ISSUE TITLE
[JB plugin] Internal error: UninitializedPropertyAccessException

### ISSUE THREAD

**Issue by rahiyansafz** [smallcloudai/refact-intellij#45]
An internal error happened in the IDE plugin.

Message: Unhandled exception in [CoroutineName(run activity), run activity, StandaloneCoroutine{Cancelling}@208b764e, Dispatchers.Default]

### Stack trace
```
kotlin.UninitializedPropertyAccessException: lateinit property instance has not been initialized
	at com.smallcloud.refactai.listeners.LastEditorGetterListener$Companion.getInstance(LastEditorGetterListener.kt:85)
	at com.smallcloud.refactai.Initializer.initialize(Initializer.kt:28)
	at com.smallcloud.refactai.Initializer.execute(Initializer.kt:25)
	at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1.invokeSuspend(StartupManagerImpl.kt:482)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(run activity), run activity, StandaloneCoroutine{Cancelled}@208b764e, Dispatchers.Default]

```

### Environment
- Plugin version: 1.2.3
- IDE: JetBrains Rider 2023.3 EAP 8  Build #RD-233.11799.49
- JDK: 17.0.9; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
- OS: Windows 10.0
- MODE: Cloud

**Comment by reymondzzzz** [comment]
#43 same
