### ISSUE TITLE
[JB plugin] Internal error: Default]

### ISSUE THREAD

**Issue by AsimutMLS** [smallcloudai/refact-intellij#47]
An internal error happened in the IDE plugin.

Message: *** exception class was changed or removed

### Stack trace
```
  Unhandled exception in [CoroutineName(com.smallcloud.refactai.Initializer), StandaloneCoroutine{Cancelling}@8920189, Dispatchers.Default]
  
  java.nio.file.AccessDeniedException: C:\Users\Asimut\.refact\bin\refact-lsp.exe
at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
at java.base/java.nio.file.Files.deleteIfExists(Files.java:1191)
at java.base/java.nio.file.Files.copy(Files.java:3148)
at com.smallcloud.refactai.lsp.LSPProcessHolder.startup(LSPProcessHolder.kt:101)
at com.smallcloud.refactai.Initializer.initialize(Initializer.kt:55)
at com.smallcloud.refactai.Initializer.execute(Initializer.kt:25)
at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1$1.invokeSuspend(StartupManagerImpl.kt:534)
at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1$1.invoke(StartupManagerImpl.kt)
at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1$1.invoke(StartupManagerImpl.kt)
at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1.invokeSuspend(StartupManagerImpl.kt:532)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(com.smallcloud.refactai.Initializer), StandaloneCoroutine{Cancelled}@8920189, Dispatchers.Default]

```

### Environment
- Plugin version: 1.2.3
- IDE: IntelliJ IDEA 2023.2.5  Build #IU-232.10227.8
- JDK: 17.0.9; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
- OS: Windows 10.0
- MODE: Cloud

**Comment by reymondzzzz** [comment]
#44 same
