### ISSUE TITLE
[JB plugin] High CPU usage and Internal error: Throwable

### ISSUE THREAD

**Issue by ricardas-buc** [smallcloudai/refact-intellij#54]
An internal error happened in the IDE plugin.

Message: (no message)

### Stack trace
```
java.lang.Throwable: Assert: must be called on EDT
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at com.intellij.util.ui.EDT.assertIsEdt(EDT.java:68)
	at com.intellij.codeInsight.hint.LocalHintManager.getHintPosition(LocalHintManager.java:346)
	at com.intellij.codeInsight.hint.HintManagerImpl.showInformationHint(HintManagerImpl.java:486)
	at com.intellij.codeInsight.hint.HintManagerImpl.showInformationHint(HintManagerImpl.java:460)
	at com.intellij.codeInsight.hint.HintManagerImpl.showInformationHint(HintManagerImpl.java:452)
	at com.intellij.openapi.editor.EditorModificationUtil.checkModificationAllowed(EditorModificationUtil.java:148)
	at com.smallcloud.refactai.modes.completion.CompletionMode.shouldIgnoreChange(CompletionMode.kt:322)
	at com.smallcloud.refactai.modes.completion.CompletionMode.onTextChange(CompletionMode.kt:93)
	at com.smallcloud.refactai.modes.ModeProvider.checkAndSendEvents(ModeProvider.kt:97)
	at com.smallcloud.refactai.modes.ModeProvider._init_$lambda$0(ModeProvider.kt:71)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:275)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:215)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

### Environment
- Plugin version: 1.2.4
- IDE: IntelliJ IDEA 2023.2.5  Build #IU-232.10227.8
- JDK: 17.0.9; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
- OS: macOS 14.1.1
- ARCH: aarch64
- MODE: Cloud

### Additional information

This exception is thrown when closing on of the open projects.
In addition, CPU usage for the plugin is usually high.

<img width="1184" alt="image" src="https://github.com/smallcloudai/refact-intellij/assets/2776864/ccca7e0e-eabc-40fc-8db1-a02f13cb5e91">
IntelliJ was 99% idling during this time:
<img width="585" alt="image" src="https://github.com/smallcloudai/refact-intellij/assets/2776864/2cdf1875-d709-4f09-b1a7-c9914364458c">

On freshly started IntelliJ cpu usage is <1%

**Comment by reymondzzzz** [comment]
Hi! Thanks for report and good work! I have similar situation without refact plugin. Could try IDEA without plugin and turn sleep mode your computer. I think it's connected to JVM specific work... Thanks again :)
