### ISSUE TITLE
[JB plugin] Internal error: Default]

### ISSUE THREAD

**Issue by choff5507** [smallcloudai/refact-intellij#59]
An internal error happened in the IDE plugin.

Message: *** exception class was changed or removed

### Stack trace
```
   Unhandled exception in [CoroutineName(com.smallcloud.refactai.Initializer), StandaloneCoroutine{Cancelling}@1bbf4e2e, Dispatchers.Default]
   
   com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "/Users/charles/.refact/bin/refact-lsp": error=86, Bad CPU type in executable
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:356)
	at com.smallcloud.refactai.lsp.LSPProcessHolder.startProcess(LSPProcessHolder.kt:163)
	at com.smallcloud.refactai.lsp.LSPProcessHolder.settingsChanged(LSPProcessHolder.kt:136)
	at com.smallcloud.refactai.lsp.LSPProcessHolder.startup(LSPProcessHolder.kt:107)
	at com.smallcloud.refactai.Initializer.initialize(Initializer.kt:52)
	at com.smallcloud.refactai.Initializer.execute(Initializer.kt:25)
	at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1$1.invokeSuspend(StartupManagerImpl.kt:534)
	at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1$1.invoke(StartupManagerImpl.kt)
	at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1$1.invoke(StartupManagerImpl.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1.invokeSuspend(StartupManagerImpl.kt:532)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(com.smallcloud.refactai.Initializer), StandaloneCoroutine{Cancelled}@1bbf4e2e, Dispatchers.Default]
Caused by: java.io.IOException: Cannot run program "/Users/charles/.refact/bin/refact-lsp": error=86, Bad CPU type in executable
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:432)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:346)
	... 18 more
Caused by: java.io.IOException: error=86, Bad CPU type in executable
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 21 more

```

### Environment
- Plugin version: 1.2.4
- IDE: PhpStorm 2023.2.4  Build #PS-232.10227.13
- JDK: 17.0.9; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
- OS: macOS 14.1.2
- ARCH: aarch64
- MODE: Cloud

**Comment by reymondzzzz** [comment]
#44 same

**Comment by reymondzzzz** [comment]
Hi! try new 1.2.5 version. Hope it helps you.

**Comment by reymondzzzz** [comment]
Hi! Thanks for report! Unfortunately, default GH doesn't support arm worker for mac. Right now it is x86_64 and it works in m1 cpu. How did you disable this virtualization?
