### ISSUE TITLE
[JB plugin] Internal error: AccessDeniedException

### ISSUE THREAD

**Issue by exon1704** [smallcloudai/refact-intellij#67]
An internal error happened in the IDE plugin.

Message: Unhandled exception in [CoroutineName(run activity), run activity, StandaloneCoroutine{Cancelling}@30a01925, Dispatchers.Default]

### Stack trace
```
java.nio.file.AccessDeniedException: C:\Users\exon\AppData\Local\Temp\refact-lsp.exe
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
	at java.base/java.nio.file.Files.deleteIfExists(Files.java:1191)
	at java.base/java.nio.file.Files.copy(Files.java:3148)
	at com.smallcloud.refactai.lsp.LSPProcessHolder.startup(LSPProcessHolder.kt:102)
	at com.smallcloud.refactai.Initializer.initialize(Initializer.kt:52)
	at com.smallcloud.refactai.Initializer.execute(Initializer.kt:25)
	at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1.invokeSuspend(StartupManagerImpl.kt:482)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(run activity), run activity, StandaloneCoroutine{Cancelled}@30a01925, Dispatchers.Default]

```

### Environment
- Plugin version: 1.2.5
- IDE: WebStorm 2023.3  Build #WS-233.11799.229
- JDK: 17.0.9; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
- OS: Windows 10.0
- ARCH: amd64
- MODE: Cloud

**Comment by reymondzzzz** [comment]
dublicate #44
