### ISSUE TITLE
[JB plugin] Internal error: AssertionError

### ISSUE THREAD

**Issue by xmasuhai** [smallcloudai/refact-intellij#77]
An internal error happened in the IDE plugin.

Message: (no message)

### Stack trace
```
java.lang.AssertionError: hostname can't be null
	at com.intellij.openapi.diagnostic.DefaultLogger.error(DefaultLogger.java:83)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:436)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.setException(SchedulingWrapper.java:288)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:275)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:244)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:222)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.IllegalArgumentException: hostname can't be null
	at java.base/java.net.InetSocketAddress.checkHost(InetSocketAddress.java:158)
	at java.base/java.net.InetSocketAddress.<init>(InetSocketAddress.java:225)
	at com.intellij.util.net.IdeaWideProxySelector.select(IdeaWideProxySelector.java:51)
	at com.intellij.util.proxy.CommonProxy.select(CommonProxy.java:215)
	at com.intellij.util.proxy.CommonProxy.select(CommonProxy.java:180)
	at com.intellij.util.net.HttpConfigurable.openConnection(HttpConfigurable.java:377)
	at com.intellij.openapi.fileEditor.impl.IdeUiServiceImpl.openHttpConnection(IdeUiServiceImpl.java:138)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:558)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:361)
	at com.intellij.util.io.HttpRequests$Request.write(HttpRequests.java:116)
	at com.intellij.util.io.HttpRequests$Request.write(HttpRequests.java:112)
	at com.smallcloud.refactai.UpdateChecker.checkNewVersion$lambda$1(UpdateChecker.kt:59)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:524)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:506)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:335)
	at com.smallcloud.refactai.UpdateChecker.checkNewVersion(UpdateChecker.kt:58)
	at com.smallcloud.refactai.UpdateChecker._init_$lambda$0(UpdateChecker.kt:33)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	... 13 more

```

### Environment
- Plugin version: 1.2.8
- IDE: WebStorm 2023.3.1  Build #WS-233.11799.293
- JDK: 17.0.9; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
- OS: Windows 11.0
- ARCH: amd64
- MODE: Cloud

**Comment by reymondzzzz** [comment]
#76
